// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NominaAPEC.Data;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace NominaAPEC.Migrations
{
    [DbContext(typeof(MyDbContext))]
    [Migration("20241127025225_AddEmpleadoIdAndTipoTransaccionToAsientoContable")]
    partial class AddEmpleadoIdAndTipoTransaccionToAsientoContable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("NominaAPEC.Models.AsientoContable", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CuentaCR")
                        .HasColumnType("integer");

                    b.Property<int>("CuentaDB")
                        .HasColumnType("integer");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("EmpleadoId")
                        .HasColumnType("integer");

                    b.Property<bool>("Estado")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("FechaAsiento")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("IdAuxiliar")
                        .HasColumnType("integer");

                    b.Property<decimal>("Monto")
                        .HasColumnType("numeric");

                    b.Property<string>("TipoTransaccion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("asientoscontables", (string)null);
                });

            modelBuilder.Entity("NominaAPEC.Models.Empleado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Cedula")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("cedula");

                    b.Property<string>("Departamento")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("departamento");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nombre");

                    b.Property<int>("NominaId")
                        .HasColumnType("integer")
                        .HasColumnName("nominaid");

                    b.Property<string>("Puesto")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("puesto");

                    b.Property<decimal>("SalarioMensual")
                        .HasColumnType("numeric")
                        .HasColumnName("salariomensual");

                    b.HasKey("Id");

                    b.ToTable("empleados", (string)null);
                });

            modelBuilder.Entity("NominaAPEC.Models.RegistroTransaccion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("EmpleadoId")
                        .HasColumnType("integer")
                        .HasColumnName("empleadoid");

                    b.Property<short>("Estado")
                        .HasColumnType("smallint")
                        .HasColumnName("estado");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("fecha");

                    b.Property<int>("IdAsiento")
                        .HasColumnType("integer")
                        .HasColumnName("idasiento");

                    b.Property<decimal>("Monto")
                        .HasColumnType("numeric")
                        .HasColumnName("monto");

                    b.Property<int?>("TipoDeduccionId")
                        .HasColumnType("integer")
                        .HasColumnName("tipodeduccionid");

                    b.Property<int?>("TipoIngresoId")
                        .HasColumnType("integer")
                        .HasColumnName("tipoingresoid");

                    b.Property<string>("TipoTransaccion")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tipotransaccion");

                    b.HasKey("Id");

                    b.HasIndex("EmpleadoId");

                    b.HasIndex("TipoDeduccionId");

                    b.HasIndex("TipoIngresoId");

                    b.ToTable("registrotransacciones", (string)null);
                });

            modelBuilder.Entity("NominaAPEC.Models.TipoDeduccion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<short>("DependeDeSalario")
                        .HasColumnType("smallint")
                        .HasColumnName("dependedesalario");

                    b.Property<short>("Estado")
                        .HasColumnType("smallint")
                        .HasColumnName("estado");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nombre");

                    b.HasKey("Id");

                    b.ToTable("tiposdeduccion", (string)null);
                });

            modelBuilder.Entity("NominaAPEC.Models.TipoIngreso", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<short>("DependeDeSalario")
                        .HasColumnType("smallint")
                        .HasColumnName("dependedesalario");

                    b.Property<short>("Estado")
                        .HasColumnType("smallint")
                        .HasColumnName("estado");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nombre");

                    b.Property<string>("Trial710")
                        .HasColumnType("character")
                        .HasColumnName("trial710");

                    b.HasKey("Id");

                    b.ToTable("tiposingreso", (string)null);
                });

            modelBuilder.Entity("NominaAPEC.Models.RegistroTransaccion", b =>
                {
                    b.HasOne("NominaAPEC.Models.Empleado", "Empleado")
                        .WithMany()
                        .HasForeignKey("EmpleadoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NominaAPEC.Models.TipoDeduccion", "TipoDeduccion")
                        .WithMany()
                        .HasForeignKey("TipoDeduccionId");

                    b.HasOne("NominaAPEC.Models.TipoIngreso", "TipoIngreso")
                        .WithMany()
                        .HasForeignKey("TipoIngresoId");

                    b.Navigation("Empleado");

                    b.Navigation("TipoDeduccion");

                    b.Navigation("TipoIngreso");
                });
#pragma warning restore 612, 618
        }
    }
}
